#!/usr/bin/env python
from configFromFile import configurator
conf = configurator(2)
conf.checkMirrorConfigAccuracy('config.conf')
conf.checkSyncConfigAccuracy('sync.conf')
res = conf.generateSyncCommands('sync.conf','config.conf')
conf.generateExcutables(res)