#!/bin/bash

filename=`basename $0`

# create the lock
if [ -f _syncLock ] 
then 
	linecount=`wc -l _syncLock | grep -E '[[:digit:]]+' -o`
	if [ $linecount -eq %(maxThreadNum)% ]
	then
		echo 'sync blocked ...'
		echo -e $filename"\tskipped\t"$(date +%F_%T) >>  %(syncLog)%
		exit -1
	fi		
	for line in `cat _syncLock`
	do
		if [ $line == $filename ]
		then
			echo 'sync blocked ...'
			echo -e $filename"\tskipped\t"$(date +%F_%T) >> %(syncLog)%
			exit -1
		fi
	done
fi
echo $filename >> _syncLock

# sync
set -o pipefail
startSyncTime=$(date +%s)
echo '==== sync '$filename' start ===='
timeout %(timeout)%h %(syncTool)% %(parameter)% %(configFileName)% mirror | tee %(logPath)%/${filename}"_"$(date +%F_%T)".log"
sleep 2
stopSyncTime=$(date +%s)
if [ $((stopSyncTime-startSyncTime)) -gt $((%(timeout)%*3600)) ]
then
	#sync timeout
	echo -e $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
else
	todoFile=%(syncPath)%/todo
	if [ -f $todoFile ]
	then
		lineCount=`wc -l $todoFile | grep -E '[[:digit:]]+' -o`
		if [ $lineCount -ne 0 ]
		then
			#sync fail
			echo -e $filename"\tfailed\t"$(date +%F_%T) >> %(syncLog)%
		else
			#sync succeeded
			echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
		fi
	else
		#sync succeeded
		echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
	fi
fi

echo '==== sync '$filename' stop ===='

# remove the lock
if [ ! -f __syncLock ]
then
	touch __syncLock
fi

for line in `cat _syncLock`
do
	if [ $line != $filename ]
	then
		echo $line >> __syncLock
	fi
done

mv __syncLock _syncLock
