#!/bin/bash
filename=`basename $0`

# create the lock
if [ -f _syncLock ] 
then 
	linecount=`wc -l _syncLock | grep -E '[[:digit:]]+' -o`
	if [ $linecount -eq %(maxThreadNum)% ]
	then
		echo 'sync blocked ...'
		echo -e $filename"\tskipped\t"$(date +%F_%T) >>  %(syncLog)%
		exit -1
	fi
	for line in `cat _syncLock`
	do
		if [ $line == $filename ]
		then
			echo 'sync blocked ...'
			echo -e $filename"\tskipped\t"$(date +%F_%T) >> %(syncLog)%
			exit -1
		fi
	done
fi
echo $filename >> _syncLock

# before sync comands here <--------------------------------------------------------

# sync
currentPath=$PWD

#record the start sync time
startSyncTime=$(date +%s)
set -o pipefail

echo '==== sync '$filename' start ===='
timeout --preserve-status %(timeout)%h %(synctool)%        | tee %(logpath)%/${filename}"_"$(date +%F_%T)".log"
                                                  #  ^^^^<---enter the sync command here <-----------
result=$?

# record the stop sync time
sleep 2
stopSyncTime=$(date+%s)

# go back to the Script path
cd $currentPath
if [ $((stopSyncTime-startSyncTime)) -gt $((%(timeout)%*3600)) ]
then
	echo -e $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
else
	if [ $result -eq 0 ]	#<------ modify success judgement here <-------------------
	then
		#sync succeeded
		echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
	else
		#sync failed
		echo -e $filename"\tfailed\t"$(date +%F_%T) >> %(syncLog)%
	fi
fi

# after sync commands here <-------------------------------------------------------
echo '==== sync '$filename' stop ===='

# remove the lock
if [ ! -f __syncLock ]
then
	touch __syncLock
fi

for line in `cat _syncLock`
do
	if [ $line != $filename ]
	then
		echo $line >> __syncLock
	fi
done

mv __syncLock _syncLock
