#!/bin/sh
filename=`basename $0`

# create the lock
if [ -f _syncLock ] 
then 
	linecount=`wc -l _syncLock | grep -E '[[:digit:]]+' -o`
	if [ $linecount -eq %(maxThreadNum)% ]
	then
		echo 'sync blocked ...'
		echo -e $filename"\tskipped\t"$(date +%F_%T) >>  %(syncLog)%
		exit -1
	fi
	for line in `cat _syncLock`
	do
		if [ $line == $filename ]
		then
			echo 'sync blocked ...'
			echo -e $filename"\tskipped\t"$(date +%F_%T) >> %(syncLog)%
			exit -1
		fi
	done
fi
echo $filename >> _syncLock

excuted=0
if [ -f _executeOnceLock ]
then
	for name in `cat _excuteOnceLock`
	do
		if [ $name == $filename ]
		then
			excuted=1
		fi
	done
fi

if [ $excuted -eq 0 ]
then
	# excute once commands here <----------------------------------------------
	echo $filename >> _excuteOnceLock
fi

# before sync comands here <--------------------------------------------------------

# sync
echo '==== sync '$filename' start ===='
timeout %(timeout)% %(synctool)% # enter the sync command here <--------------------

if [ $? -eq 124 ]
then
	#sync timeout
	echo -e $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
else
	#sync succeeded
	echo -e $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
fi

# after sync commands here <-------------------------------------------------------
echo '==== sync '$filename' stop ===='

# remove the lock
if [ ! -f __syncLock ]
then
	touch __syncLock
fi

for line in `cat _syncLock`
do
	if [ $line != $filename ]
	then
		echo $line >> __syncLock
	fi
done

mv __syncLock _syncLock
