#!/bin/sh

echo '
[mirror]
directory = %(syncPath)%
master = %(url)%
timeout = 30
workers = 2
; Note that package index directory hashing is incompatible with pip
hash-index = false
stop-on-error = false
delete-packages = true
;log-config = %(logFileName)%

[statistics]
access-log-pattern = /var/log/nginx/*.pypi.python.org*access*
' > %(configFileName)%

filename=`basename $0`

# create the lock
if [ -f _syncLock ] 
then 
	linecount=`wc -l _syncLock | grep -E '[[:digit:]]+' -o`
	if [ $linecount -eq %(maxThreadNum)% ]
	then
		echo 'sync blocked ...'
		echo $filename"\tskipped\t"$(date +%F_%T) >>  %(syncLog)%
		exit -1
	fi
fi
echo $filename >> _syncLock

# sync
echo '==== sync '$filename' start ===='
timeout %(timeout)% %(syncTool)% %(parameter)% %(configFileName)% mirror

if [ $? -eq 124 ]
then
	#sync timeout
	echo $filename"\ttimeout\t"$(date +%F_%T) >> %(syncLog)%
else
	#sync succeeded
	echo $filename"\tsucceed\t"$(date +%F_%T) >> %(syncLog)%
fi

echo '==== sync '$filename' stop ===='

# remove the lock
if [ ! -f __syncLock ]
then
	touch __syncLock
fi

for line in `cat _syncLock`
do
	if [ $line != $filename ]
	then
		echo line >> __syncLock
	fi
done

mv __syncLock _syncLock
