#!/bin/sh
filename=`basename $0`

# create the lock
if [ -f _syncLock ] 
then 
	linecount=`wc -l _syncLock | grep -E '[[:digit:]]+' -o`
	if [ linecount -eq %(maxThreadNum)% ]
	then
		echo 'sync blocked ...'
		return -1
	fi
else
	echo $filename >> _syncLock
fi

# sync
echo '==== sync '$filename' start ===='
timeout %(timeout)% %(syncTool)% %(defaultRsyncParameter)% %(parameter)% %(url)% %(syncPath)%
echo '==== sync '$filename' stop ===='

#check if sync succeeded


# remove the lock
if [ ! -f __syncLock ]
then
	touch __syncLock
fi

for line in `cat _syncLock`
do
	if [ $line != $filename ]
	then
		echo line >> __syncLock
	fi
done

mv __syncLock _syncLock
